name: digital_canteen
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #  Navigation - dont update
  auto_route: ^9.3.0+1

  # State Management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # UI 
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5


  # UTILS
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  logger: ^2.5.0
  equatable: ^2.0.7

  
  # FIREBASE PLUGINS
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15


flutter:
  uses-material-design: true

  assets:
    - assets/images/